-- ============================================================
-- COAR CONNECT - BASE DE DATOS ACADÉMICA
-- Ejecutar DESPUÉS de 00_DDL_drop_tables_coar_connect.sql
-- PostgreSQL 15+ | Base de datos: coar_connect | Schema: public
-- ============================================================

-- ============================================================
-- BLOQUE 0: EXTENSIONES
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- BLOQUE 1: CATÁLOGOS BASE
-- ============================================================

CREATE TABLE ROLES (
    PKROL SERIAL PRIMARY KEY,
    CODROL CHAR(3) NOT NULL UNIQUE,
    NOMROL VARCHAR(50) NOT NULL,
    DESROL VARCHAR(150),
    ESTADO CHAR(1) NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE DISTRITOS (
    PKDISTRITO SERIAL PRIMARY KEY,
    CODDISTRITO CHAR(6) NOT NULL UNIQUE,
    DEPARTAMENTO VARCHAR(60) NOT NULL,
    PROVINCIA VARCHAR(60) NOT NULL,
    DISTRITO VARCHAR(60) NOT NULL,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE GRADOS_ACADEMICOS (
    PKGRADO SERIAL PRIMARY KEY,
    CODGRADO CHAR(3) NOT NULL UNIQUE,
    DESGRADO VARCHAR(50) NOT NULL,
    NIVEL VARCHAR(40) NOT NULL DEFAULT 'Secundaria',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE PARENTESCOS (
    PKPARENTESCO SERIAL PRIMARY KEY,
    CODPARENTESCO CHAR(3) NOT NULL UNIQUE,
    DESPARENTESCO VARCHAR(50) NOT NULL,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE AREAS_ACADEMICAS (
    PKAREAACADEMICA SERIAL PRIMARY KEY,
    CODAREAACADEMICA CHAR(3) NOT NULL UNIQUE,
    DESAREAACADEMICA VARCHAR(80) NOT NULL,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE NIVELES_CURSO (
    PKNIVELCURSO SERIAL PRIMARY KEY,
    CODNIVELCURSO CHAR(3) NOT NULL UNIQUE,
    DESNIVELCURSO VARCHAR(50) NOT NULL,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE MODALIDADES_CLASE (
    PKMODALIDADCLASE SERIAL PRIMARY KEY,
    CODMODALIDADCLASE CHAR(3) NOT NULL UNIQUE,
    DESMODALIDADCLASE VARCHAR(50) NOT NULL,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE TIPOS_MATERIAL (
    PKTIPOMATERIAL SERIAL PRIMARY KEY,
    CODTIPOMATERIAL CHAR(3) NOT NULL UNIQUE,
    DESTIPOMATERIAL VARCHAR(50) NOT NULL,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE TIPOS_SIMULACRO (
    PKTIPOSIMULACRO SERIAL PRIMARY KEY,
    CODTIPOSIMULACRO CHAR(3) NOT NULL UNIQUE,
    DESTIPOSIMULACRO VARCHAR(80) NOT NULL,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE TIPOS_EVENTO_COAR (
    PKTIPOEVENTOCOAR SERIAL PRIMARY KEY,
    CODTIPOEVENTOCOAR CHAR(3) NOT NULL UNIQUE,
    DESTIPOEVENTOCOAR VARCHAR(80) NOT NULL,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE ESTADOS_INSCRIPCION (
    PKESTADOINSCRIPCION SERIAL PRIMARY KEY,
    CODESTADOINSCRIPCION CHAR(3) NOT NULL UNIQUE,
    DESESTADOINSCRIPCION VARCHAR(50) NOT NULL,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE ESTADOS_EVALUACION (
    PKESTADOEVALUACION SERIAL PRIMARY KEY,
    CODESTADOEVALUACION CHAR(3) NOT NULL UNIQUE,
    DESESTADOEVALUACION VARCHAR(50) NOT NULL,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 2: USUARIOS Y PERFILES
-- ============================================================

CREATE TABLE USUARIOS (
    PKUSUARIO SERIAL PRIMARY KEY,
    CODUSUARIO VARCHAR(12) NOT NULL UNIQUE,
    NOMBRES VARCHAR(80) NOT NULL,
    APELLIDOS VARCHAR(80) NOT NULL,
    CORREO VARCHAR(120) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20),
    PKROL INT NOT NULL REFERENCES ROLES(PKROL),
    FECHAREGISTRO TIMESTAMP NOT NULL DEFAULT NOW(),
    ULTIMO_ACCESO TIMESTAMP,
    ESTADO CHAR(1) NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE ESTUDIANTES (
    PKESTUDIANTE SERIAL PRIMARY KEY,
    CODESTUDIANTE VARCHAR(12) NOT NULL UNIQUE,
    PKUSUARIO INT NOT NULL UNIQUE REFERENCES USUARIOS(PKUSUARIO) ON DELETE CASCADE,
    PKGRADO INT NOT NULL REFERENCES GRADOS_ACADEMICOS(PKGRADO),
    COLEGIO VARCHAR(120) NOT NULL,
    PKDISTRITO INT NOT NULL REFERENCES DISTRITOS(PKDISTRITO),
    PROMEDIOACTUAL NUMERIC(5,2) DEFAULT 0,
    HORASESTUDIADAS NUMERIC(6,2) DEFAULT 0,
    ESTADO CHAR(1) NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE PADRES (
    PKPADRE SERIAL PRIMARY KEY,
    CODPADRE VARCHAR(12) NOT NULL UNIQUE,
    PKUSUARIO INT NOT NULL UNIQUE REFERENCES USUARIOS(PKUSUARIO) ON DELETE CASCADE,
    OCUPACION VARCHAR(100),
    DIRECCION VARCHAR(150),
    ESTADO CHAR(1) NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE PADRES_ESTUDIANTES (
    PKPADRE INT NOT NULL REFERENCES PADRES(PKPADRE) ON DELETE CASCADE,
    PKESTUDIANTE INT NOT NULL REFERENCES ESTUDIANTES(PKESTUDIANTE) ON DELETE CASCADE,
    PKPARENTESCO INT NOT NULL REFERENCES PARENTESCOS(PKPARENTESCO),
    RESPONSABLE_PRINCIPAL CHAR(1) NOT NULL DEFAULT 'S',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PKPADRE, PKESTUDIANTE)
);

CREATE TABLE DOCENTES (
    PKDOCENTE SERIAL PRIMARY KEY,
    CODDOCENTE VARCHAR(12) NOT NULL UNIQUE,
    PKUSUARIO INT NOT NULL UNIQUE REFERENCES USUARIOS(PKUSUARIO) ON DELETE CASCADE,
    ESPECIALIDAD VARCHAR(100) NOT NULL,
    EXPERIENCIA VARCHAR(150),
    ESTADO CHAR(1) NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE SESIONES_USUARIO (
    PKSESION BIGSERIAL PRIMARY KEY,
    PKUSUARIO INT NOT NULL REFERENCES USUARIOS(PKUSUARIO) ON DELETE CASCADE,
    TOKEN_REFRESH VARCHAR(500),
    FECHAINICIO TIMESTAMP NOT NULL DEFAULT NOW(),
    FECHAFIN TIMESTAMP,
    IP_ACCESO VARCHAR(50),
    ACTIVA CHAR(1) NOT NULL DEFAULT 'S',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 3: CURSOS, HORARIOS E INSCRIPCIONES
-- ============================================================

CREATE TABLE CURSOS (
    PKCURSO SERIAL PRIMARY KEY,
    CODCURSO VARCHAR(10) NOT NULL UNIQUE,
    NOMCURSO VARCHAR(100) NOT NULL,
    DESCURSO TEXT,
    PKAREAACADEMICA INT NOT NULL REFERENCES AREAS_ACADEMICAS(PKAREAACADEMICA),
    PKNIVELCURSO INT NOT NULL REFERENCES NIVELES_CURSO(PKNIVELCURSO),
    PKDOCENTE INT REFERENCES DOCENTES(PKDOCENTE) ON DELETE SET NULL,
    IMAGEN_URL TEXT,
    ESTADO CHAR(1) NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE HORARIOS (
    PKHORARIO SERIAL PRIMARY KEY,
    CODHORARIO VARCHAR(12) NOT NULL UNIQUE,
    PKCURSO INT NOT NULL REFERENCES CURSOS(PKCURSO) ON DELETE CASCADE,
    DIA_SEMANA VARCHAR(20) NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    PKMODALIDADCLASE INT NOT NULL REFERENCES MODALIDADES_CLASE(PKMODALIDADCLASE),
    CUPOS INT NOT NULL DEFAULT 0 CHECK (CUPOS >= 0),
    ESTADO CHAR(1) NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW(),
    CHECK (HORA_FIN > HORA_INICIO)
);

CREATE TABLE INSCRIPCIONES (
    PKINSCRIPCION SERIAL PRIMARY KEY,
    CODINSCRIPCION VARCHAR(12) NOT NULL UNIQUE,
    PKESTUDIANTE INT NOT NULL REFERENCES ESTUDIANTES(PKESTUDIANTE) ON DELETE CASCADE,
    PKHORARIO INT NOT NULL REFERENCES HORARIOS(PKHORARIO) ON DELETE CASCADE,
    PKESTADOINSCRIPCION INT NOT NULL REFERENCES ESTADOS_INSCRIPCION(PKESTADOINSCRIPCION),
    FECHAINSCRIPCION TIMESTAMP NOT NULL DEFAULT NOW(),
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (PKESTUDIANTE, PKHORARIO)
);

-- ============================================================
-- BLOQUE 4: MATERIALES EDUCATIVOS
-- ============================================================

CREATE TABLE MATERIALES (
    PKMATERIAL SERIAL PRIMARY KEY,
    CODMATERIAL VARCHAR(12) NOT NULL UNIQUE,
    PKCURSO INT NOT NULL REFERENCES CURSOS(PKCURSO) ON DELETE CASCADE,
    PKDOCENTE INT REFERENCES DOCENTES(PKDOCENTE) ON DELETE SET NULL,
    PKTIPOMATERIAL INT NOT NULL REFERENCES TIPOS_MATERIAL(PKTIPOMATERIAL),
    TITULO VARCHAR(150) NOT NULL,
    DESCRIPCION TEXT,
    ARCHIVO_URL TEXT NOT NULL,
    FECHASUBIDA TIMESTAMP NOT NULL DEFAULT NOW(),
    ESTADO CHAR(1) NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE MATERIAL_VISUALIZADO (
    PKMATERIAL INT NOT NULL REFERENCES MATERIALES(PKMATERIAL) ON DELETE CASCADE,
    PKESTUDIANTE INT NOT NULL REFERENCES ESTUDIANTES(PKESTUDIANTE) ON DELETE CASCADE,
    FECHAVISUALIZACION TIMESTAMP NOT NULL DEFAULT NOW(),
    COMPLETADO CHAR(1) NOT NULL DEFAULT 'N',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PKMATERIAL, PKESTUDIANTE)
);

-- ============================================================
-- BLOQUE 5: SIMULACROS Y EVALUACIONES
-- ============================================================

CREATE TABLE SIMULACROS (
    PKSIMULACRO SERIAL PRIMARY KEY,
    CODSIMULACRO VARCHAR(12) NOT NULL UNIQUE,
    TITULO VARCHAR(150) NOT NULL,
    DESCRIPCION TEXT,
    PKCURSO INT REFERENCES CURSOS(PKCURSO) ON DELETE SET NULL,
    PKTIPOSIMULACRO INT NOT NULL REFERENCES TIPOS_SIMULACRO(PKTIPOSIMULACRO),
    TIEMPO_MINUTOS INT NOT NULL CHECK (TIEMPO_MINUTOS > 0),
    FECHAPUBLICACION DATE NOT NULL DEFAULT CURRENT_DATE,
    ESTADO CHAR(1) NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE PREGUNTAS (
    PKPREGUNTA SERIAL PRIMARY KEY,
    PKSIMULACRO INT NOT NULL REFERENCES SIMULACROS(PKSIMULACRO) ON DELETE CASCADE,
    ENUNCIADO TEXT NOT NULL,
    PUNTAJE NUMERIC(5,2) NOT NULL DEFAULT 1 CHECK (PUNTAJE > 0),
    ORDEN INT NOT NULL DEFAULT 1,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE ALTERNATIVAS (
    PKALTERNATIVA SERIAL PRIMARY KEY,
    PKPREGUNTA INT NOT NULL REFERENCES PREGUNTAS(PKPREGUNTA) ON DELETE CASCADE,
    TEXTO TEXT NOT NULL,
    ES_CORRECTA CHAR(1) NOT NULL DEFAULT 'N',
    ORDEN INT NOT NULL DEFAULT 1,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE RESULTADOS (
    PKRESULTADO SERIAL PRIMARY KEY,
    CODRESULTADO VARCHAR(12) NOT NULL UNIQUE,
    PKESTUDIANTE INT NOT NULL REFERENCES ESTUDIANTES(PKESTUDIANTE) ON DELETE CASCADE,
    PKSIMULACRO INT NOT NULL REFERENCES SIMULACROS(PKSIMULACRO) ON DELETE CASCADE,
    PKESTADOEVALUACION INT NOT NULL REFERENCES ESTADOS_EVALUACION(PKESTADOEVALUACION),
    PUNTAJE NUMERIC(6,2) NOT NULL DEFAULT 0 CHECK (PUNTAJE >= 0),
    NOTA_VIGESIMAL NUMERIC(5,2) DEFAULT 0 CHECK (NOTA_VIGESIMAL >= 0),
    FECHAINICIO TIMESTAMP,
    FECHAFIN TIMESTAMP,
    OBSERVACION TEXT,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE RESPUESTAS_ESTUDIANTE (
    PKRESPUESTA SERIAL PRIMARY KEY,
    PKRESULTADO INT NOT NULL REFERENCES RESULTADOS(PKRESULTADO) ON DELETE CASCADE,
    PKPREGUNTA INT NOT NULL REFERENCES PREGUNTAS(PKPREGUNTA) ON DELETE CASCADE,
    PKALTERNATIVA INT REFERENCES ALTERNATIVAS(PKALTERNATIVA) ON DELETE SET NULL,
    ES_CORRECTA CHAR(1) NOT NULL DEFAULT 'N',
    PUNTAJE_OBTENIDO NUMERIC(5,2) NOT NULL DEFAULT 0,
    FECHARESPUESTA TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (PKRESULTADO, PKPREGUNTA)
);

CREATE TABLE RESULTADOS_SIMULACRO (
    PKRESULTADOSIMULACRO SERIAL PRIMARY KEY,
    PKRESULTADO INT NOT NULL REFERENCES RESULTADOS(PKRESULTADO) ON DELETE CASCADE,
    TOTAL_PREGUNTAS INT NOT NULL DEFAULT 0,
    RESPUESTAS_CORRECTAS INT NOT NULL DEFAULT 0,
    RESPUESTAS_INCORRECTAS INT NOT NULL DEFAULT 0,
    PORCENTAJE_LOGRO NUMERIC(5,2) DEFAULT 0 CHECK (PORCENTAJE_LOGRO BETWEEN 0 AND 100),
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 6: SEGUIMIENTO ACADÉMICO
-- ============================================================

CREATE TABLE SEGUIMIENTO_ACADEMICO (
    PKSEGUIMIENTO SERIAL PRIMARY KEY,
    CODSEGUIMIENTO VARCHAR(12) NOT NULL UNIQUE,
    PKESTUDIANTE INT NOT NULL REFERENCES ESTUDIANTES(PKESTUDIANTE) ON DELETE CASCADE,
    FECHAREGISTRO DATE NOT NULL DEFAULT CURRENT_DATE,
    HORAS_ESTUDIADAS NUMERIC(6,2) DEFAULT 0 CHECK (HORAS_ESTUDIADAS >= 0),
    PROMEDIO_GENERAL NUMERIC(5,2) DEFAULT 0 CHECK (PROMEDIO_GENERAL >= 0),
    AVANCE_GENERAL NUMERIC(5,2) DEFAULT 0 CHECK (AVANCE_GENERAL BETWEEN 0 AND 100),
    OBSERVACION TEXT,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE PROGRESO_CURSO (
    PKPROGRESOCURSO SERIAL PRIMARY KEY,
    PKESTUDIANTE INT NOT NULL REFERENCES ESTUDIANTES(PKESTUDIANTE) ON DELETE CASCADE,
    PKCURSO INT NOT NULL REFERENCES CURSOS(PKCURSO) ON DELETE CASCADE,
    AVANCE_PORCENTAJE NUMERIC(5,2) DEFAULT 0 CHECK (AVANCE_PORCENTAJE BETWEEN 0 AND 100),
    HORAS_ESTUDIADAS NUMERIC(6,2) DEFAULT 0 CHECK (HORAS_ESTUDIADAS >= 0),
    PROMEDIO_CURSO NUMERIC(5,2) DEFAULT 0,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (PKESTUDIANTE, PKCURSO)
);

CREATE TABLE ASISTENCIAS (
    PKASISTENCIA SERIAL PRIMARY KEY,
    PKESTUDIANTE INT NOT NULL REFERENCES ESTUDIANTES(PKESTUDIANTE) ON DELETE CASCADE,
    PKHORARIO INT NOT NULL REFERENCES HORARIOS(PKHORARIO) ON DELETE CASCADE,
    FECHA_CLASE DATE NOT NULL,
    ASISTIO CHAR(1) NOT NULL DEFAULT 'N',
    OBSERVACION TEXT,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (PKESTUDIANTE, PKHORARIO, FECHA_CLASE)
);

CREATE TABLE RECOMENDACIONES_ACADEMICAS (
    PKRECOMENDACION SERIAL PRIMARY KEY,
    PKESTUDIANTE INT NOT NULL REFERENCES ESTUDIANTES(PKESTUDIANTE) ON DELETE CASCADE,
    PKCURSO INT REFERENCES CURSOS(PKCURSO) ON DELETE SET NULL,
    RECOMENDACION TEXT NOT NULL,
    PRIORIDAD VARCHAR(20) DEFAULT 'Media',
    FECHAREGISTRO DATE NOT NULL DEFAULT CURRENT_DATE,
    ESTADO CHAR(1) NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE METAS_ESTUDIANTE (
    PKMETA SERIAL PRIMARY KEY,
    PKESTUDIANTE INT NOT NULL REFERENCES ESTUDIANTES(PKESTUDIANTE) ON DELETE CASCADE,
    TITULO VARCHAR(120) NOT NULL,
    DESCRIPCION TEXT,
    FECHAINICIO DATE NOT NULL DEFAULT CURRENT_DATE,
    FECHAFIN DATE,
    COMPLETADO CHAR(1) NOT NULL DEFAULT 'N',
    PORCENTAJE_AVANCE NUMERIC(5,2) DEFAULT 0 CHECK (PORCENTAJE_AVANCE BETWEEN 0 AND 100),
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 7: CALENDARIO Y NOTIFICACIONES
-- ============================================================

CREATE TABLE CALENDARIO_COAR (
    PKCALENDARIOCOAR SERIAL PRIMARY KEY,
    CODCALENDARIO VARCHAR(12) NOT NULL UNIQUE,
    TITULO VARCHAR(150) NOT NULL,
    DESCRIPCION TEXT,
    FECHA_EVENTO DATE NOT NULL,
    PKTIPOEVENTOCOAR INT NOT NULL REFERENCES TIPOS_EVENTO_COAR(PKTIPOEVENTOCOAR),
    VISIBLE_ESTUDIANTE CHAR(1) NOT NULL DEFAULT 'S',
    VISIBLE_PADRE CHAR(1) NOT NULL DEFAULT 'S',
    ESTADO CHAR(1) NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE NOTIFICACIONES (
    PKNOTIFICACION SERIAL PRIMARY KEY,
    PKUSUARIO INT NOT NULL REFERENCES USUARIOS(PKUSUARIO) ON DELETE CASCADE,
    TITULO VARCHAR(120) NOT NULL,
    MENSAJE TEXT NOT NULL,
    FECHAENVIO TIMESTAMP NOT NULL DEFAULT NOW(),
    LEIDO CHAR(1) NOT NULL DEFAULT 'N',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 8: GAMIFICACIÓN Y LOGROS
-- ============================================================

CREATE TABLE MEDALLAS (
    PKMEDALLA SERIAL PRIMARY KEY,
    CODMEDALLA VARCHAR(10) NOT NULL UNIQUE,
    NOMMEDALLA VARCHAR(80) NOT NULL,
    DESMEDALLA VARCHAR(150),
    ICONO_URL TEXT,
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE ESTUDIANTE_MEDALLA (
    PKESTUDIANTE INT NOT NULL REFERENCES ESTUDIANTES(PKESTUDIANTE) ON DELETE CASCADE,
    PKMEDALLA INT NOT NULL REFERENCES MEDALLAS(PKMEDALLA) ON DELETE CASCADE,
    FECHAOBTENCION TIMESTAMP NOT NULL DEFAULT NOW(),
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PKESTUDIANTE, PKMEDALLA)
);

CREATE TABLE HORARIO_RECOMENDADO (
    PKHORARIORECOMENDADO SERIAL PRIMARY KEY,
    PKESTUDIANTE INT NOT NULL REFERENCES ESTUDIANTES(PKESTUDIANTE) ON DELETE CASCADE,
    PKCURSO INT NOT NULL REFERENCES CURSOS(PKCURSO) ON DELETE CASCADE,
    DIA_SEMANA VARCHAR(20) NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    MOTIVO TEXT,
    ACTIVO CHAR(1) NOT NULL DEFAULT 'S',
    FECULTACTUALIZACION TIMESTAMP NOT NULL DEFAULT NOW(),
    CHECK (HORA_FIN > HORA_INICIO)
);

-- ============================================================
-- BLOQUE 9: ÍNDICES ESTRATÉGICOS
-- ============================================================

CREATE INDEX IX_USUARIOS_ROL ON USUARIOS(PKROL);
CREATE INDEX IX_USUARIOS_CORREO ON USUARIOS(CORREO);

CREATE INDEX IX_ESTUDIANTES_USUARIO ON ESTUDIANTES(PKUSUARIO);
CREATE INDEX IX_ESTUDIANTES_GRADO ON ESTUDIANTES(PKGRADO);
CREATE INDEX IX_ESTUDIANTES_DISTRITO ON ESTUDIANTES(PKDISTRITO);

CREATE INDEX IX_PADRES_USUARIO ON PADRES(PKUSUARIO);
CREATE INDEX IX_PADRES_ESTUDIANTES_EST ON PADRES_ESTUDIANTES(PKESTUDIANTE);

CREATE INDEX IX_DOCENTES_USUARIO ON DOCENTES(PKUSUARIO);

CREATE INDEX IX_CURSOS_DOCENTE ON CURSOS(PKDOCENTE);
CREATE INDEX IX_CURSOS_AREA ON CURSOS(PKAREAACADEMICA);
CREATE INDEX IX_HORARIOS_CURSO ON HORARIOS(PKCURSO);

CREATE INDEX IX_INSCRIPCIONES_EST ON INSCRIPCIONES(PKESTUDIANTE);
CREATE INDEX IX_INSCRIPCIONES_HOR ON INSCRIPCIONES(PKHORARIO);

CREATE INDEX IX_MATERIALES_CURSO ON MATERIALES(PKCURSO);
CREATE INDEX IX_MATERIAL_VIS_EST ON MATERIAL_VISUALIZADO(PKESTUDIANTE);

CREATE INDEX IX_SIMULACROS_CURSO ON SIMULACROS(PKCURSO);
CREATE INDEX IX_PREGUNTAS_SIMULACRO ON PREGUNTAS(PKSIMULACRO);
CREATE INDEX IX_ALTERNATIVAS_PREGUNTA ON ALTERNATIVAS(PKPREGUNTA);

CREATE INDEX IX_RESULTADOS_EST ON RESULTADOS(PKESTUDIANTE);
CREATE INDEX IX_RESULTADOS_SIM ON RESULTADOS(PKSIMULACRO);

CREATE INDEX IX_SEGUIMIENTO_EST ON SEGUIMIENTO_ACADEMICO(PKESTUDIANTE);
CREATE INDEX IX_PROGRESO_EST_CURSO ON PROGRESO_CURSO(PKESTUDIANTE, PKCURSO);

CREATE INDEX IX_ASISTENCIAS_EST ON ASISTENCIAS(PKESTUDIANTE);
CREATE INDEX IX_ASISTENCIAS_HOR ON ASISTENCIAS(PKHORARIO);

CREATE INDEX IX_CALENDARIO_FECHA ON CALENDARIO_COAR(FECHA_EVENTO);
CREATE INDEX IX_NOTIFICACIONES_USUARIO ON NOTIFICACIONES(PKUSUARIO);

-- ============================================================
-- VERIFICACIÓN OPCIONAL
-- ============================================================

-- SELECT tablename
-- FROM pg_tables
-- WHERE schemaname = 'public'
-- ORDER BY tablename;