-- ============================================================
-- COAR CONNECT - 04_DML_CURSOS_HORARIOS.SQL
-- Cursos, horarios e inscripciones iniciales
-- Ejecutar después de 03_DML_usuarios_perfiles_coar_connect.sql
-- PostgreSQL 15+ | Base de datos: coar_connect
-- ============================================================

BEGIN;

-- ============================================================
-- BLOQUE 1: CURSOS DE REFORZAMIENTO
-- ============================================================

INSERT INTO CURSOS (
    CODCURSO, NOMCURSO, DESCURSO, PKAREAACADEMICA,
    PKNIVELCURSO, PKDOCENTE, IMAGEN_URL
) VALUES
('CUR000001','Matemática Básica COAR',
 'Curso de reforzamiento en operaciones, fracciones, porcentajes y resolución de problemas.',
 (SELECT PKAREAACADEMICA FROM AREAS_ACADEMICAS WHERE CODAREAACADEMICA='MAT'),
 (SELECT PKNIVELCURSO FROM NIVELES_CURSO WHERE CODNIVELCURSO='BAS'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000001'),
 '/imagenes/cursos/matematica_basica.png'),

('CUR000002','Razonamiento Matemático',
 'Curso orientado al desarrollo de lógica, series, patrones y problemas tipo admisión COAR.',
 (SELECT PKAREAACADEMICA FROM AREAS_ACADEMICAS WHERE CODAREAACADEMICA='RMT'),
 (SELECT PKNIVELCURSO FROM NIVELES_CURSO WHERE CODNIVELCURSO='INT'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000001'),
 '/imagenes/cursos/razonamiento_matematico.png'),

('CUR000003','Comunicación',
 'Curso de comprensión lectora, análisis de textos y producción escrita.',
 (SELECT PKAREAACADEMICA FROM AREAS_ACADEMICAS WHERE CODAREAACADEMICA='COM'),
 (SELECT PKNIVELCURSO FROM NIVELES_CURSO WHERE CODNIVELCURSO='BAS'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000002'),
 '/imagenes/cursos/comunicacion.png'),

('CUR000004','Razonamiento Verbal',
 'Curso para fortalecer analogías, inferencias, sinónimos, antónimos y comprensión verbal.',
 (SELECT PKAREAACADEMICA FROM AREAS_ACADEMICAS WHERE CODAREAACADEMICA='RVM'),
 (SELECT PKNIVELCURSO FROM NIVELES_CURSO WHERE CODNIVELCURSO='INT'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000002'),
 '/imagenes/cursos/razonamiento_verbal.png'),

('CUR000005','Ciencia y Tecnología',
 'Curso de ciencias naturales, pensamiento científico y resolución de problemas contextualizados.',
 (SELECT PKAREAACADEMICA FROM AREAS_ACADEMICAS WHERE CODAREAACADEMICA='CYT'),
 (SELECT PKNIVELCURSO FROM NIVELES_CURSO WHERE CODNIVELCURSO='BAS'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000003'),
 '/imagenes/cursos/ciencia_tecnologia.png'),

('CUR000006','Inglés Básico',
 'Curso introductorio de vocabulario, lectura y comprensión básica en inglés.',
 (SELECT PKAREAACADEMICA FROM AREAS_ACADEMICAS WHERE CODAREAACADEMICA='ING'),
 (SELECT PKNIVELCURSO FROM NIVELES_CURSO WHERE CODNIVELCURSO='BAS'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000004'),
 '/imagenes/cursos/ingles_basico.png'),

('CUR000007','Preparación General COAR',
 'Curso integral con orientación sobre el proceso de admisión, hábitos de estudio y estrategias.',
 (SELECT PKAREAACADEMICA FROM AREAS_ACADEMICAS WHERE CODAREAACADEMICA='GEN'),
 (SELECT PKNIVELCURSO FROM NIVELES_CURSO WHERE CODNIVELCURSO='PRE'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000005'),
 '/imagenes/cursos/preparacion_general.png');

-- ============================================================
-- BLOQUE 2: HORARIOS DE CLASE
-- ============================================================

INSERT INTO HORARIOS (
    CODHORARIO, PKCURSO, DIA_SEMANA, HORA_INICIO, HORA_FIN,
    PKMODALIDADCLASE, CUPOS
) VALUES
('HOR000001',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000001'),
 'Lunes','16:00','17:30',
 (SELECT PKMODALIDADCLASE FROM MODALIDADES_CLASE WHERE CODMODALIDADCLASE='VIR'),
 30),

('HOR000002',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000002'),
 'Martes','16:00','17:30',
 (SELECT PKMODALIDADCLASE FROM MODALIDADES_CLASE WHERE CODMODALIDADCLASE='VIR'),
 30),

('HOR000003',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000003'),
 'Miércoles','16:00','17:30',
 (SELECT PKMODALIDADCLASE FROM MODALIDADES_CLASE WHERE CODMODALIDADCLASE='VIR'),
 30),

('HOR000004',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000004'),
 'Jueves','16:00','17:30',
 (SELECT PKMODALIDADCLASE FROM MODALIDADES_CLASE WHERE CODMODALIDADCLASE='VIR'),
 30),

('HOR000005',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000005'),
 'Viernes','16:00','17:30',
 (SELECT PKMODALIDADCLASE FROM MODALIDADES_CLASE WHERE CODMODALIDADCLASE='VIR'),
 30),

('HOR000006',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000006'),
 'Sábado','09:00','10:30',
 (SELECT PKMODALIDADCLASE FROM MODALIDADES_CLASE WHERE CODMODALIDADCLASE='VIR'),
 30),

('HOR000007',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000007'),
 'Sábado','11:00','12:30',
 (SELECT PKMODALIDADCLASE FROM MODALIDADES_CLASE WHERE CODMODALIDADCLASE='VIR'),
 40),

('HOR000008',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000001'),
 'Lunes','18:00','19:30',
 (SELECT PKMODALIDADCLASE FROM MODALIDADES_CLASE WHERE CODMODALIDADCLASE='GRA'),
 100),

('HOR000009',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000003'),
 'Miércoles','18:00','19:30',
 (SELECT PKMODALIDADCLASE FROM MODALIDADES_CLASE WHERE CODMODALIDADCLASE='GRA'),
 100),

('HOR000010',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000005'),
 'Viernes','18:00','19:30',
 (SELECT PKMODALIDADCLASE FROM MODALIDADES_CLASE WHERE CODMODALIDADCLASE='GRA'),
 100);

-- ============================================================
-- BLOQUE 3: INSCRIPCIONES INICIALES
-- ============================================================

INSERT INTO INSCRIPCIONES (
    CODINSCRIPCION, PKESTUDIANTE, PKHORARIO, PKESTADOINSCRIPCION
) VALUES
('INS000001',
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000001'),
 (SELECT PKHORARIO FROM HORARIOS WHERE CODHORARIO='HOR000001'),
 (SELECT PKESTADOINSCRIPCION FROM ESTADOS_INSCRIPCION WHERE CODESTADOINSCRIPCION='ACT')),

('INS000002',
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000001'),
 (SELECT PKHORARIO FROM HORARIOS WHERE CODHORARIO='HOR000003'),
 (SELECT PKESTADOINSCRIPCION FROM ESTADOS_INSCRIPCION WHERE CODESTADOINSCRIPCION='ACT')),

('INS000003',
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000002'),
 (SELECT PKHORARIO FROM HORARIOS WHERE CODHORARIO='HOR000002'),
 (SELECT PKESTADOINSCRIPCION FROM ESTADOS_INSCRIPCION WHERE CODESTADOINSCRIPCION='ACT')),

('INS000004',
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000003'),
 (SELECT PKHORARIO FROM HORARIOS WHERE CODHORARIO='HOR000004'),
 (SELECT PKESTADOINSCRIPCION FROM ESTADOS_INSCRIPCION WHERE CODESTADOINSCRIPCION='ACT')),

('INS000005',
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000004'),
 (SELECT PKHORARIO FROM HORARIOS WHERE CODHORARIO='HOR000005'),
 (SELECT PKESTADOINSCRIPCION FROM ESTADOS_INSCRIPCION WHERE CODESTADOINSCRIPCION='ACT')),

('INS000006',
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000005'),
 (SELECT PKHORARIO FROM HORARIOS WHERE CODHORARIO='HOR000006'),
 (SELECT PKESTADOINSCRIPCION FROM ESTADOS_INSCRIPCION WHERE CODESTADOINSCRIPCION='ACT')),

('INS000007',
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000006'),
 (SELECT PKHORARIO FROM HORARIOS WHERE CODHORARIO='HOR000007'),
 (SELECT PKESTADOINSCRIPCION FROM ESTADOS_INSCRIPCION WHERE CODESTADOINSCRIPCION='ACT')),

('INS000008',
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000007'),
 (SELECT PKHORARIO FROM HORARIOS WHERE CODHORARIO='HOR000001'),
 (SELECT PKESTADOINSCRIPCION FROM ESTADOS_INSCRIPCION WHERE CODESTADOINSCRIPCION='ACT')),

('INS000009',
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000008'),
 (SELECT PKHORARIO FROM HORARIOS WHERE CODHORARIO='HOR000002'),
 (SELECT PKESTADOINSCRIPCION FROM ESTADOS_INSCRIPCION WHERE CODESTADOINSCRIPCION='ACT')),

('INS000010',
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000008'),
 (SELECT PKHORARIO FROM HORARIOS WHERE CODHORARIO='HOR000004'),
 (SELECT PKESTADOINSCRIPCION FROM ESTADOS_INSCRIPCION WHERE CODESTADOINSCRIPCION='ACT'));

-- ============================================================
-- BLOQUE 4: HORARIO RECOMENDADO
-- Para el módulo de recomendaciones del estudiante
-- ============================================================

INSERT INTO HORARIO_RECOMENDADO (
    PKESTUDIANTE, PKCURSO, DIA_SEMANA, HORA_INICIO, HORA_FIN, MOTIVO
) VALUES
((SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000001'),
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000001'),
 'Lunes','19:30','20:30',
 'Reforzar matemática básica por bajo avance en ejercicios'),

((SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000001'),
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000003'),
 'Miércoles','19:30','20:30',
 'Practicar comprensión lectora con textos largos'),

((SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000002'),
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000002'),
 'Martes','18:00','19:00',
 'Mejorar razonamiento lógico y patrones'),

((SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000003'),
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000004'),
 'Jueves','18:00','19:00',
 'Fortalecer vocabulario e inferencias'),

((SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000004'),
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000005'),
 'Viernes','18:00','19:00',
 'Reforzar temas de ciencia y tecnología');

-- ============================================================
-- BLOQUE 5: VERIFICACIÓN OPCIONAL
-- ============================================================

-- SELECT c.CODCURSO, c.NOMCURSO, a.DESAREAACADEMICA, n.DESNIVELCURSO
-- FROM CURSOS c
-- INNER JOIN AREAS_ACADEMICAS a ON c.PKAREAACADEMICA = a.PKAREAACADEMICA
-- INNER JOIN NIVELES_CURSO n ON c.PKNIVELCURSO = n.PKNIVELCURSO
-- ORDER BY c.PKCURSO;

-- SELECT h.CODHORARIO, c.NOMCURSO, h.DIA_SEMANA, h.HORA_INICIO, h.HORA_FIN, m.DESMODALIDADCLASE
-- FROM HORARIOS h
-- INNER JOIN CURSOS c ON h.PKCURSO = c.PKCURSO
-- INNER JOIN MODALIDADES_CLASE m ON h.PKMODALIDADCLASE = m.PKMODALIDADCLASE
-- ORDER BY h.PKHORARIO;

-- SELECT i.CODINSCRIPCION, u.NOMBRES, u.APELLIDOS, c.NOMCURSO, h.DIA_SEMANA
-- FROM INSCRIPCIONES i
-- INNER JOIN ESTUDIANTES e ON i.PKESTUDIANTE = e.PKESTUDIANTE
-- INNER JOIN USUARIOS u ON e.PKUSUARIO = u.PKUSUARIO
-- INNER JOIN HORARIOS h ON i.PKHORARIO = h.PKHORARIO
-- INNER JOIN CURSOS c ON h.PKCURSO = c.PKCURSO;

COMMIT;