-- ============================================================
-- COAR CONNECT - 03_DML_USUARIOS_PERFILES.SQL
-- Usuarios ficticios + perfiles académicos
-- Ejecutar después de 02_DML_catalogos_coar_connect.sql
-- PostgreSQL 15+ | Base de datos: coar_connect
-- ============================================================

BEGIN;

-- ============================================================
-- BLOQUE 1: USUARIOS ADMINISTRADORES
-- ============================================================

INSERT INTO USUARIOS (
    CODUSUARIO, NOMBRES, APELLIDOS, CORREO, PASSWORD_HASH, TELEFONO, PKROL
) VALUES
('USR000001','Administrador','Principal','admin@coarconnect.pe','123456','900000001',
 (SELECT PKROL FROM ROLES WHERE CODROL='ADM'));

-- ============================================================
-- BLOQUE 2: USUARIOS DOCENTES
-- ============================================================

INSERT INTO USUARIOS (
    CODUSUARIO, NOMBRES, APELLIDOS, CORREO, PASSWORD_HASH, TELEFONO, PKROL
) VALUES
('USR000002','Rosa','Quispe Huamán','rosa.quispe@coarconnect.pe','123456','900000002',
 (SELECT PKROL FROM ROLES WHERE CODROL='DOC')),
('USR000003','Luis','Mendoza Flores','luis.mendoza@coarconnect.pe','123456','900000003',
 (SELECT PKROL FROM ROLES WHERE CODROL='DOC')),
('USR000004','Carmen','Torres Rojas','carmen.torres@coarconnect.pe','123456','900000004',
 (SELECT PKROL FROM ROLES WHERE CODROL='DOC')),
('USR000005','Miguel','Soto Ramos','miguel.soto@coarconnect.pe','123456','900000005',
 (SELECT PKROL FROM ROLES WHERE CODROL='DOC')),
('USR000006','Ana','Paredes Salazar','ana.paredes@coarconnect.pe','123456','900000006',
 (SELECT PKROL FROM ROLES WHERE CODROL='DOC'));

-- ============================================================
-- BLOQUE 3: PERFIL DOCENTES
-- ============================================================

INSERT INTO DOCENTES (
    CODDOCENTE, PKUSUARIO, ESPECIALIDAD, EXPERIENCIA
) VALUES
('DOC000001',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000002'),
 'Matemática y Razonamiento Matemático',
 '5 años preparando estudiantes para admisión COAR'),

('DOC000002',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000003'),
 'Comunicación y Razonamiento Verbal',
 '4 años en reforzamiento escolar'),

('DOC000003',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000004'),
 'Ciencia y Tecnología',
 '6 años de experiencia en secundaria'),

('DOC000004',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000005'),
 'Inglés básico e intermedio',
 '3 años enseñando inglés escolar'),

('DOC000005',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000006'),
 'Orientación académica COAR',
 'Especialista en acompañamiento estudiantil');

-- ============================================================
-- BLOQUE 4: USUARIOS ESTUDIANTES
-- ============================================================

INSERT INTO USUARIOS (
    CODUSUARIO, NOMBRES, APELLIDOS, CORREO, PASSWORD_HASH, TELEFONO, PKROL
) VALUES
('USR000007','Camila','Solis Hinostroza','camila.solis@coarconnect.pe','123456','900000007',
 (SELECT PKROL FROM ROLES WHERE CODROL='EST')),
('USR000008','Diego','Ramos Quispe','diego.ramos@coarconnect.pe','123456','900000008',
 (SELECT PKROL FROM ROLES WHERE CODROL='EST')),
('USR000009','Lucía','Huamán Torres','lucia.huaman@coarconnect.pe','123456','900000009',
 (SELECT PKROL FROM ROLES WHERE CODROL='EST')),
('USR000010','Mateo','Flores Rojas','mateo.flores@coarconnect.pe','123456','900000010',
 (SELECT PKROL FROM ROLES WHERE CODROL='EST')),
('USR000011','Valeria','Paredes Soto','valeria.paredes@coarconnect.pe','123456','900000011',
 (SELECT PKROL FROM ROLES WHERE CODROL='EST')),
('USR000012','Sebastián','Mendoza Castro','sebastian.mendoza@coarconnect.pe','123456','900000012',
 (SELECT PKROL FROM ROLES WHERE CODROL='EST')),
('USR000013','María','Quispe Salazar','maria.quispe@coarconnect.pe','123456','900000013',
 (SELECT PKROL FROM ROLES WHERE CODROL='EST')),
('USR000014','Ángel','Cárdenas López','angel.cardenas@coarconnect.pe','123456','900000014',
 (SELECT PKROL FROM ROLES WHERE CODROL='EST'));

-- ============================================================
-- BLOQUE 5: PERFIL ESTUDIANTES
-- ============================================================

INSERT INTO ESTUDIANTES (
    CODESTUDIANTE, PKUSUARIO, PKGRADO, COLEGIO, PKDISTRITO,
    PROMEDIOACTUAL, HORASESTUDIADAS
) VALUES
('EST000001',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000007'),
 (SELECT PKGRADO FROM GRADOS_ACADEMICOS WHERE CODGRADO='2S'),
 'Colegio Estatal de El Tambo',
 (SELECT PKDISTRITO FROM DISTRITOS WHERE CODDISTRITO='120104'),
 15.50, 12.00),

('EST000002',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000008'),
 (SELECT PKGRADO FROM GRADOS_ACADEMICOS WHERE CODGRADO='2S'),
 'I.E. Santa Isabel',
 (SELECT PKDISTRITO FROM DISTRITOS WHERE CODDISTRITO='120101'),
 14.80, 8.50),

('EST000003',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000009'),
 (SELECT PKGRADO FROM GRADOS_ACADEMICOS WHERE CODGRADO='1S'),
 'I.E. Nuestra Señora del Rosario',
 (SELECT PKDISTRITO FROM DISTRITOS WHERE CODDISTRITO='120101'),
 16.20, 10.00),

('EST000004',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000010'),
 (SELECT PKGRADO FROM GRADOS_ACADEMICOS WHERE CODGRADO='2S'),
 'I.E. José Carlos Mariátegui',
 (SELECT PKDISTRITO FROM DISTRITOS WHERE CODDISTRITO='120106'),
 15.00, 7.50),

('EST000005',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000011'),
 (SELECT PKGRADO FROM GRADOS_ACADEMICOS WHERE CODGRADO='3S'),
 'Politécnico Regional del Centro',
 (SELECT PKDISTRITO FROM DISTRITOS WHERE CODDISTRITO='120101'),
 14.50, 6.00),

('EST000006',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000012'),
 (SELECT PKGRADO FROM GRADOS_ACADEMICOS WHERE CODGRADO='2S'),
 'I.E. Mariscal Castilla',
 (SELECT PKDISTRITO FROM DISTRITOS WHERE CODDISTRITO='120104'),
 15.80, 9.00),

('EST000007',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000013'),
 (SELECT PKGRADO FROM GRADOS_ACADEMICOS WHERE CODGRADO='1S'),
 'I.E. Túpac Amaru',
 (SELECT PKDISTRITO FROM DISTRITOS WHERE CODDISTRITO='120119'),
 16.00, 11.00),

('EST000008',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000014'),
 (SELECT PKGRADO FROM GRADOS_ACADEMICOS WHERE CODGRADO='3S'),
 'I.E. San Juan Bosco',
 (SELECT PKDISTRITO FROM DISTRITOS WHERE CODDISTRITO='120116'),
 14.90, 5.50);

-- ============================================================
-- BLOQUE 6: USUARIOS PADRES / APODERADOS
-- ============================================================

INSERT INTO USUARIOS (
    CODUSUARIO, NOMBRES, APELLIDOS, CORREO, PASSWORD_HASH, TELEFONO, PKROL
) VALUES
('USR000015','Walter','Solis','walter.solis@coarconnect.pe','123456','900000015',
 (SELECT PKROL FROM ROLES WHERE CODROL='PAD')),
('USR000016','Juana','Hinostroza','juana.hinostroza@coarconnect.pe','123456','900000016',
 (SELECT PKROL FROM ROLES WHERE CODROL='PAD')),
('USR000017','Rosa','Quispe','rosa.madre@coarconnect.pe','123456','900000017',
 (SELECT PKROL FROM ROLES WHERE CODROL='PAD')),
('USR000018','Carlos','Ramos','carlos.ramos@coarconnect.pe','123456','900000018',
 (SELECT PKROL FROM ROLES WHERE CODROL='PAD')),
('USR000019','María','Torres','maria.torres@coarconnect.pe','123456','900000019',
 (SELECT PKROL FROM ROLES WHERE CODROL='PAD')),
('USR000020','Pedro','Flores','pedro.flores@coarconnect.pe','123456','900000020',
 (SELECT PKROL FROM ROLES WHERE CODROL='PAD')),
('USR000021','Elena','Salazar','elena.salazar@coarconnect.pe','123456','900000021',
 (SELECT PKROL FROM ROLES WHERE CODROL='PAD')),
('USR000022','Jorge','Cárdenas','jorge.cardenas@coarconnect.pe','123456','900000022',
 (SELECT PKROL FROM ROLES WHERE CODROL='PAD'));

-- ============================================================
-- BLOQUE 7: PERFIL PADRES / APODERADOS
-- ============================================================

INSERT INTO PADRES (
    CODPADRE, PKUSUARIO, OCUPACION, DIRECCION
) VALUES
('PAD000001',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000015'),
 'Comerciante',
 'El Tambo - Huancayo'),

('PAD000002',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000016'),
 'Ama de casa',
 'Paccha - Huancayo'),

('PAD000003',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000017'),
 'Docente',
 'Huancayo Centro'),

('PAD000004',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000018'),
 'Transportista',
 'Chilca - Huancayo'),

('PAD000005',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000019'),
 'Comerciante',
 'El Tambo - Huancayo'),

('PAD000006',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000020'),
 'Agricultor',
 'Sapallanga - Huancayo'),

('PAD000007',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000021'),
 'Enfermera',
 'Pilcomayo - Huancayo'),

('PAD000008',
 (SELECT PKUSUARIO FROM USUARIOS WHERE CODUSUARIO='USR000022'),
 'Trabajador independiente',
 'Huancayo');

-- ============================================================
-- BLOQUE 8: RELACIÓN PADRES - ESTUDIANTES
-- ============================================================

INSERT INTO PADRES_ESTUDIANTES (
    PKPADRE, PKESTUDIANTE, PKPARENTESCO, RESPONSABLE_PRINCIPAL
) VALUES
((SELECT PKPADRE FROM PADRES WHERE CODPADRE='PAD000001'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000001'),
 (SELECT PKPARENTESCO FROM PARENTESCOS WHERE CODPARENTESCO='PAD'),
 'S'),

((SELECT PKPADRE FROM PADRES WHERE CODPADRE='PAD000002'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000001'),
 (SELECT PKPARENTESCO FROM PARENTESCOS WHERE CODPARENTESCO='MAD'),
 'N'),

((SELECT PKPADRE FROM PADRES WHERE CODPADRE='PAD000003'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000002'),
 (SELECT PKPARENTESCO FROM PARENTESCOS WHERE CODPARENTESCO='MAD'),
 'S'),

((SELECT PKPADRE FROM PADRES WHERE CODPADRE='PAD000004'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000003'),
 (SELECT PKPARENTESCO FROM PARENTESCOS WHERE CODPARENTESCO='PAD'),
 'S'),

((SELECT PKPADRE FROM PADRES WHERE CODPADRE='PAD000005'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000004'),
 (SELECT PKPARENTESCO FROM PARENTESCOS WHERE CODPARENTESCO='MAD'),
 'S'),

((SELECT PKPADRE FROM PADRES WHERE CODPADRE='PAD000006'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000005'),
 (SELECT PKPARENTESCO FROM PARENTESCOS WHERE CODPARENTESCO='PAD'),
 'S'),

((SELECT PKPADRE FROM PADRES WHERE CODPADRE='PAD000007'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000006'),
 (SELECT PKPARENTESCO FROM PARENTESCOS WHERE CODPARENTESCO='MAD'),
 'S'),

((SELECT PKPADRE FROM PADRES WHERE CODPADRE='PAD000008'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000007'),
 (SELECT PKPARENTESCO FROM PARENTESCOS WHERE CODPARENTESCO='PAD'),
 'S');

-- ============================================================
-- BLOQUE 9: VERIFICACIÓN RÁPIDA
-- ============================================================

-- SELECT u.CODUSUARIO, u.NOMBRES, u.APELLIDOS, r.NOMROL
-- FROM USUARIOS u
-- INNER JOIN ROLES r ON u.PKROL = r.PKROL
-- ORDER BY u.PKUSUARIO;

-- SELECT e.CODESTUDIANTE, u.NOMBRES, u.APELLIDOS, e.COLEGIO
-- FROM ESTUDIANTES e
-- INNER JOIN USUARIOS u ON e.PKUSUARIO = u.PKUSUARIO;

-- SELECT p.CODPADRE, up.NOMBRES AS padre, ue.NOMBRES AS estudiante, par.DESPARENTESCO
-- FROM PADRES_ESTUDIANTES pe
-- INNER JOIN PADRES p ON pe.PKPADRE = p.PKPADRE
-- INNER JOIN USUARIOS up ON p.PKUSUARIO = up.PKUSUARIO
-- INNER JOIN ESTUDIANTES e ON pe.PKESTUDIANTE = e.PKESTUDIANTE
-- INNER JOIN USUARIOS ue ON e.PKUSUARIO = ue.PKUSUARIO
-- INNER JOIN PARENTESCOS par ON pe.PKPARENTESCO = par.PKPARENTESCO;

COMMIT;