-- ============================================================
-- COAR CONNECT - 05_DML_MATERIALES_SIMULACROS.SQL
-- Materiales educativos + simulacros + preguntas
-- Ejecutar después de 04_DML_cursos_horarios_coar_connect.sql
-- PostgreSQL 15+ | Base de datos: coar_connect
-- ============================================================

BEGIN;

-- ============================================================
-- BLOQUE 1: MATERIALES EDUCATIVOS
-- ============================================================

INSERT INTO MATERIALES (
    CODMATERIAL, PKCURSO, PKDOCENTE, PKTIPOMATERIAL,
    TITULO, DESCRIPCION, ARCHIVO_URL
) VALUES
('MAT000001',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000001'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000001'),
 (SELECT PKTIPOMATERIAL FROM TIPOS_MATERIAL WHERE CODTIPOMATERIAL='PDF'),
 'Guía de Matemática Básica COAR',
 'Material introductorio con ejercicios de operaciones, fracciones y porcentajes.',
 '/materiales/matematica/guia_matematica_basica.pdf'),

('MAT000002',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000001'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000001'),
 (SELECT PKTIPOMATERIAL FROM TIPOS_MATERIAL WHERE CODTIPOMATERIAL='GUI'),
 'Práctica de Fracciones y Porcentajes',
 'Ejercicios guiados para reforzar problemas frecuentes en admisión COAR.',
 '/materiales/matematica/practica_fracciones_porcentajes.pdf'),

('MAT000003',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000002'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000001'),
 (SELECT PKTIPOMATERIAL FROM TIPOS_MATERIAL WHERE CODTIPOMATERIAL='PDF'),
 'Razonamiento Matemático - Series y Patrones',
 'Material con ejercicios de lógica, series numéricas y patrones.',
 '/materiales/razonamiento/series_patrones.pdf'),

('MAT000004',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000003'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000002'),
 (SELECT PKTIPOMATERIAL FROM TIPOS_MATERIAL WHERE CODTIPOMATERIAL='PDF'),
 'Comprensión Lectora Básica',
 'Lecturas cortas con preguntas de comprensión literal e inferencial.',
 '/materiales/comunicacion/comprension_lectora_basica.pdf'),

('MAT000005',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000004'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000002'),
 (SELECT PKTIPOMATERIAL FROM TIPOS_MATERIAL WHERE CODTIPOMATERIAL='GUI'),
 'Analogías y Sinónimos',
 'Práctica de razonamiento verbal con analogías, sinónimos y antónimos.',
 '/materiales/verbal/analogias_sinonimos.pdf'),

('MAT000006',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000005'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000003'),
 (SELECT PKTIPOMATERIAL FROM TIPOS_MATERIAL WHERE CODTIPOMATERIAL='PDF'),
 'Ciencia y Tecnología - Introducción',
 'Conceptos básicos de ciencias para postulantes al COAR.',
 '/materiales/ciencia/ciencia_tecnologia_intro.pdf'),

('MAT000007',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000006'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000004'),
 (SELECT PKTIPOMATERIAL FROM TIPOS_MATERIAL WHERE CODTIPOMATERIAL='PDF'),
 'Inglés Básico - Vocabulary',
 'Material de vocabulario y comprensión básica en inglés.',
 '/materiales/ingles/vocabulary_basic.pdf'),

('MAT000008',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000007'),
 (SELECT PKDOCENTE FROM DOCENTES WHERE CODDOCENTE='DOC000005'),
 (SELECT PKTIPOMATERIAL FROM TIPOS_MATERIAL WHERE CODTIPOMATERIAL='PPT'),
 'Orientación para Postulantes COAR',
 'Presentación sobre hábitos de estudio y organización semanal.',
 '/materiales/general/orientacion_postulantes.pptx');

-- ============================================================
-- BLOQUE 2: MATERIAL VISUALIZADO POR ESTUDIANTES
-- ============================================================

INSERT INTO MATERIAL_VISUALIZADO (
    PKMATERIAL, PKESTUDIANTE, COMPLETADO
) VALUES
((SELECT PKMATERIAL FROM MATERIALES WHERE CODMATERIAL='MAT000001'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000001'),
 'S'),

((SELECT PKMATERIAL FROM MATERIALES WHERE CODMATERIAL='MAT000002'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000001'),
 'N'),

((SELECT PKMATERIAL FROM MATERIALES WHERE CODMATERIAL='MAT000004'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000001'),
 'S'),

((SELECT PKMATERIAL FROM MATERIALES WHERE CODMATERIAL='MAT000003'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000002'),
 'S'),

((SELECT PKMATERIAL FROM MATERIALES WHERE CODMATERIAL='MAT000005'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000003'),
 'N'),

((SELECT PKMATERIAL FROM MATERIALES WHERE CODMATERIAL='MAT000006'),
 (SELECT PKESTUDIANTE FROM ESTUDIANTES WHERE CODESTUDIANTE='EST000004'),
 'S');

-- ============================================================
-- BLOQUE 3: SIMULACROS
-- ============================================================

INSERT INTO SIMULACROS (
    CODSIMULACRO, TITULO, DESCRIPCION, PKCURSO,
    PKTIPOSIMULACRO, TIEMPO_MINUTOS, FECHAPUBLICACION
) VALUES
('SIM000001',
 'Simulacro Matemática 01',
 'Primer simulacro de matemática básica para postulantes COAR.',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000001'),
 (SELECT PKTIPOSIMULACRO FROM TIPOS_SIMULACRO WHERE CODTIPOSIMULACRO='CUR'),
 60,
 '2026-07-10'),

('SIM000002',
 'Simulacro Comunicación 01',
 'Simulacro de comprensión lectora y razonamiento verbal inicial.',
 (SELECT PKCURSO FROM CURSOS WHERE CODCURSO='CUR000003'),
 (SELECT PKTIPOSIMULACRO FROM TIPOS_SIMULACRO WHERE CODTIPOSIMULACRO='CUR'),
 60,
 '2026-07-12'),

('SIM000003',
 'Diagnóstico Inicial COAR',
 'Evaluación inicial para medir el nivel de preparación del estudiante.',
 NULL,
 (SELECT PKTIPOSIMULACRO FROM TIPOS_SIMULACRO WHERE CODTIPOSIMULACRO='DIA'),
 90,
 '2026-07-05'),

('SIM000004',
 'Simulacro General COAR 01',
 'Evaluación integral con preguntas de matemática, comunicación y ciencia.',
 NULL,
 (SELECT PKTIPOSIMULACRO FROM TIPOS_SIMULACRO WHERE CODTIPOSIMULACRO='GEN'),
 120,
 '2026-07-20');

-- ============================================================
-- BLOQUE 4: PREGUNTAS DE SIMULACROS
-- ============================================================

INSERT INTO PREGUNTAS (
    PKSIMULACRO, ENUNCIADO, PUNTAJE, ORDEN
) VALUES
((SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001'),
 'Si un estudiante resuelve 12 ejercicios de 20, ¿qué porcentaje resolvió?',
 2, 1),

((SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001'),
 'Calcula: 3/4 + 1/2.',
 2, 2),

((SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001'),
 'Si una mochila cuesta S/80 y tiene 25% de descuento, ¿cuánto se paga?',
 2, 3),

((SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000002'),
 'Lee el texto y señala la idea principal del párrafo.',
 2, 1),

((SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000002'),
 'Elige el sinónimo de la palabra "constante".',
 2, 2),

((SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000003'),
 '¿Cuál es el principal objetivo de un horario de estudio?',
 2, 1),

((SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000004'),
 'Un estudiante estudia 2 horas diarias durante 5 días. ¿Cuántas horas estudió en total?',
 2, 1),

((SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000004'),
 'Selecciona la alternativa que representa una inferencia correcta en un texto.',
 2, 2);

-- ============================================================
-- BLOQUE 5: ALTERNATIVAS
-- ============================================================

INSERT INTO ALTERNATIVAS (
    PKPREGUNTA, TEXTO, ES_CORRECTA, ORDEN
) VALUES
-- Pregunta 1
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=1 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 '40%', 'N', 1),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=1 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 '50%', 'N', 2),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=1 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 '60%', 'S', 3),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=1 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 '80%', 'N', 4),

-- Pregunta 2
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=2 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 '1/4', 'N', 1),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=2 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 '5/4', 'S', 2),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=2 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 '2/6', 'N', 3),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=2 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 '3/8', 'N', 4),

-- Pregunta 3
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=3 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 'S/20', 'N', 1),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=3 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 'S/60', 'S', 2),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=3 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 'S/70', 'N', 3),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=3 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000001')),
 'S/100', 'N', 4),

-- Pregunta comunicación 1
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=1 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000002')),
 'La idea más importante del texto.', 'S', 1),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=1 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000002')),
 'Una palabra secundaria.', 'N', 2),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=1 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000002')),
 'Una opinión sin relación.', 'N', 3),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=1 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000002')),
 'Un dato aislado.', 'N', 4),

-- Pregunta comunicación 2
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=2 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000002')),
 'Variable', 'N', 1),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=2 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000002')),
 'Permanente', 'S', 2),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=2 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000002')),
 'Débil', 'N', 3),
((SELECT PKPREGUNTA FROM PREGUNTAS WHERE ORDEN=2 AND PKSIMULACRO=(SELECT PKSIMULACRO FROM SIMULACROS WHERE CODSIMULACRO='SIM000002')),
 'Rápido', 'N', 4);

-- ============================================================
-- BLOQUE 6: VERIFICACIÓN OPCIONAL
-- ============================================================

-- SELECT m.CODMATERIAL, m.TITULO, c.NOMCURSO
-- FROM MATERIALES m
-- INNER JOIN CURSOS c ON m.PKCURSO = c.PKCURSO
-- ORDER BY m.PKMATERIAL;

-- SELECT s.CODSIMULACRO, s.TITULO, ts.DESTIPOSIMULACRO
-- FROM SIMULACROS s
-- INNER JOIN TIPOS_SIMULACRO ts ON s.PKTIPOSIMULACRO = ts.PKTIPOSIMULACRO
-- ORDER BY s.PKSIMULACRO;

-- SELECT s.TITULO, p.ORDEN, p.ENUNCIADO
-- FROM PREGUNTAS p
-- INNER JOIN SIMULACROS s ON p.PKSIMULACRO = s.PKSIMULACRO
-- ORDER BY s.PKSIMULACRO, p.ORDEN;

COMMIT;