SELECT COUNT(*)
FROM information_schema.tables
WHERE table_schema = 'public';

SELECT *
FROM ROLES;

SELECT
    r.NOMROL,
    COUNT(*) AS TOTAL
FROM USUARIOS u
INNER JOIN ROLES r
ON u.PKROL = r.PKROL
GROUP BY r.NOMROL
ORDER BY r.NOMROL;



SELECT
    e.CODESTUDIANTE,
    u.NOMBRES,
    u.APELLIDOS,
    g.DESGRADO,
    e.COLEGIO
FROM ESTUDIANTES e
INNER JOIN USUARIOS u
ON e.PKUSUARIO = u.PKUSUARIO
INNER JOIN GRADOS_ACADEMICOS g
ON e.PKGRADO = g.PKGRADO;



SELECT
    up.NOMBRES AS PADRE,
    ue.NOMBRES AS ESTUDIANTE,
    p.DESPARENTESCO
FROM PADRES_ESTUDIANTES pe
INNER JOIN PADRES pa
ON pe.PKPADRE = pa.PKPADRE
INNER JOIN USUARIOS up
ON pa.PKUSUARIO = up.PKUSUARIO
INNER JOIN ESTUDIANTES es
ON pe.PKESTUDIANTE = es.PKESTUDIANTE
INNER JOIN USUARIOS ue
ON es.PKUSUARIO = ue.PKUSUARIO
INNER JOIN PARENTESCOS p
ON pe.PKPARENTESCO = p.PKPARENTESCO;


SELECT
    c.CODCURSO,
    c.NOMCURSO,
    u.NOMBRES || ' ' || u.APELLIDOS AS DOCENTE
FROM CURSOS c
INNER JOIN DOCENTES d
ON c.PKDOCENTE = d.PKDOCENTE
INNER JOIN USUARIOS u
ON d.PKUSUARIO = u.PKUSUARIO;


SELECT
    c.NOMCURSO,
    h.DIA_SEMANA,
    h.HORA_INICIO,
    h.HORA_FIN
FROM HORARIOS h
INNER JOIN CURSOS c
ON h.PKCURSO = c.PKCURSO;


SELECT
    u.NOMBRES,
    c.NOMCURSO
FROM INSCRIPCIONES i
INNER JOIN ESTUDIANTES e
ON i.PKESTUDIANTE = e.PKESTUDIANTE
INNER JOIN USUARIOS u
ON e.PKUSUARIO = u.PKUSUARIO
INNER JOIN HORARIOS h
ON i.PKHORARIO = h.PKHORARIO
INNER JOIN CURSOS c
ON h.PKCURSO = c.PKCURSO;

SELECT
    c.NOMCURSO,
    m.TITULO
FROM MATERIALES m
INNER JOIN CURSOS c
ON m.PKCURSO = c.PKCURSO;

SELECT
    CODSIMULACRO,
    TITULO,
    TIEMPO_MINUTOS
FROM SIMULACROS;


SELECT
    s.TITULO,
    COUNT(*) AS TOTAL_PREGUNTAS
FROM PREGUNTAS p
INNER JOIN SIMULACROS s
ON p.PKSIMULACRO = s.PKSIMULACRO
GROUP BY s.TITULO;


SELECT
    u.NOMBRES,
    s.TITULO,
    r.NOTA_VIGESIMAL
FROM RESULTADOS r
INNER JOIN ESTUDIANTES e
ON r.PKESTUDIANTE = e.PKESTUDIANTE
INNER JOIN USUARIOS u
ON e.PKUSUARIO = u.PKUSUARIO
INNER JOIN SIMULACROS s
ON r.PKSIMULACRO = s.PKSIMULACRO;


SELECT
    u.NOMBRES,
    s.PROMEDIO_GENERAL,
    s.AVANCE_GENERAL
FROM SEGUIMIENTO_ACADEMICO s
INNER JOIN ESTUDIANTES e
ON s.PKESTUDIANTE = e.PKESTUDIANTE
INNER JOIN USUARIOS u
ON e.PKUSUARIO = u.PKUSUARIO;


SELECT
    up.NOMBRES AS PADRE,
    ue.NOMBRES AS ESTUDIANTE,
    sa.PROMEDIO_GENERAL,
    sa.AVANCE_GENERAL
FROM PADRES_ESTUDIANTES pe
INNER JOIN PADRES p
ON pe.PKPADRE = p.PKPADRE
INNER JOIN USUARIOS up
ON p.PKUSUARIO = up.PKUSUARIO
INNER JOIN ESTUDIANTES e
ON pe.PKESTUDIANTE = e.PKESTUDIANTE
INNER JOIN USUARIOS ue
ON e.PKUSUARIO = ue.PKUSUARIO
INNER JOIN SEGUIMIENTO_ACADEMICO sa
ON e.PKESTUDIANTE = sa.PKESTUDIANTE;



SELECT
    u.NOMBRES,
    COUNT(DISTINCT i.PKINSCRIPCION) AS CURSOS_INSCRITOS,
    COUNT(DISTINCT mv.PKMATERIAL) AS MATERIALES_REVISADOS,
    COUNT(DISTINCT r.PKRESULTADO) AS SIMULACROS_RENDIDOS,
    MAX(sa.PROMEDIO_GENERAL) AS PROMEDIO
FROM ESTUDIANTES e
INNER JOIN USUARIOS u
ON e.PKUSUARIO = u.PKUSUARIO
LEFT JOIN INSCRIPCIONES i
ON e.PKESTUDIANTE = i.PKESTUDIANTE
LEFT JOIN MATERIAL_VISUALIZADO mv
ON e.PKESTUDIANTE = mv.PKESTUDIANTE
LEFT JOIN RESULTADOS r
ON e.PKESTUDIANTE = r.PKESTUDIANTE
LEFT JOIN SEGUIMIENTO_ACADEMICO sa
ON e.PKESTUDIANTE = sa.PKESTUDIANTE
GROUP BY u.NOMBRES;


